package uz.muhammadyusuf.kurbonov.myclinic.api.customer_search

data class User(
    val __v: Int,
    val _id: String,
    val allowLogin: Boolean,
    val avatar: DoctorAvatar,
    val avatar_id: String,
    val balance: Int,
    val birthDate: String,
    val blocked: Boolean,
    val can_delete: Boolean,
    val can_update: Boolean,
    val color: String,
    val companyId: String,
    val createdAt: String,
    val deleted: Boolean,
    val email: String,
    val firstName: String,
    val gender: String,
    val isVerified: Boolean,
    val lastName: String,
    val primaryPhone: String,
    val `public`: Boolean,
    val revenuePercent: RevenuePercent,
    val role: Role,
    val roleId: String,
    val schedule: List<Schedule>,
    val source: Source,
    val specialty: Specialty,
    val specialtyId: String,
    val treatmentNames: List<TreatmentName>,
    val treatments: List<String>,
    val updatedAt: String,
    val verifyExpires: String,
    val verifyToken: String
)