name: Run Unit tests
on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Cache gradle deps cache
        uses: actions/cache@v2
        with:
          path: |
            ./gradle/wrapper
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}3
          restore-keys: ${{ runner.os }}-gradle-3


      - name: "Gradle wrapper install"
        run: gradle wrapper
      - uses: gradle/wrapper-validation-action@v1

      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ./app/google-services.json

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew assembleDebug

      - name: Zip build
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r repo.zip ./
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: workflow_build
          path: repo.zip
          retention-days: 1

  unitTests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built
        uses: actions/download-artifact@v2
        with:
          name: workflow_build
      - name: Unzip downloaded archive
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq repo.zip -d ./

      - name: Unit Test
        run: ./gradlew test

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

  androidTests:
    runs-on: macos-latest
    needs: build
    steps:
      - name: Download built
        uses: actions/download-artifact@v2
        with:
          name: workflow_build
      - name: Unzip downloaded archive
        uses: montudor/action-zip@v1
        with:
          args: unzip -qq repo.zip -d ./

      - name: run android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck