name: Run Unit tests
on: [ push ]

jobs:
  Unit-tests:
    runs-on: self-hosted
    container:
      image: docker://fabernovel/android:api-29-v1.1.1
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Cache gradle deps cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}3
          restore-keys: ${{ runner.os }}-gradle-3

      - name: "Gradle wrapper verify"
        uses: gradle/wrapper-validation-action@v1

      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ./app/google-services.json

      #      - name: Unit Test
      #        run: ./gradlew test

      - run: apt update && apt install sudo

      # Download & install the Android SDK.
      - uses: malinskiy/action-android/install-sdk@release/0.1.2

      # Set up platform tools like adb.
      - run: sdkmanager platform-tools

      # Start ADB (and verify that pathing is working correctly).
      - run: adb devices

      - name: run tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: ./gradlew checkAndroidConnected
          api: 25

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
