name: Run Unit tests
on: [ push ]

jobs:
  androidTests:
    runs-on: self-hosted
    container:
      image: docker://fabernovel/android:api-29-v1.1.1
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11


      - name: Cache gradle deps cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}3
          restore-keys: ${{ runner.os }}-gradle-3

      - name: "Gradle wrapper verify"
        uses: gradle/wrapper-validation-action@v1

      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ./app/google-services.json

      #      - name: Unit Test
      #        run: ./gradlew test

      - name: install docker
        run: |
          apt-get -qq update

          apt-get -qq install \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg \
              lsb-release

          curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          apt-get -qq update
          apt-get -qq install docker-ce docker-ce-cli containerd.io


      - name: run emulator
        run: docker run -d -e ADBKEY="$(cat ~/.android/adbkey)" --device /dev/kvm --publish 8554:8554/tcp --publish 5555:5555/tcp us-docker.pkg.dev/android-emulator-268719/images/30-google-x64:30.1.2

      - name: connect to device
        run: adb connect localhost:5555 && adb wait-for-device

      - name: run android tests
        run: ./gradlew checkAndroidConnected

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
