name: Run Unit tests
on: [ push ]

jobs:
  Unit-tests:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache gradle deps cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}3
          restore-keys: ${{ runner.os }}-gradle-3

      - name: "Gradle wrapper verify"
        uses: gradle/wrapper-validation-action@v1

      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo $FIREBASE_SECRET > ./app/google-services.json

      - name: Unit Test
        run: ./gradlew test

      - name: run tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.2
        with:
          cmd: ./gradlew checkAndroidConnected
          api: 30

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless
